import streamlit as st
import pandas as pd
from fpdf import FPDF
import os
from datetime import datetime
import numpy as np

# 1. Comprehensive IS 1498 Data Dictionary
IS_DATA = {
    "GW": ("Well-graded gravel", "Excellent base material, high shear strength."),
    "GP": ("Poorly graded gravel", "Uniform sizes, requires good compaction."),
    "GM": ("Silty gravel", "Fair foundation, monitor moisture for frost."),
    "GC": ("Clayey gravel", "Excellent stability, low permeability."),
    "SW": ("Well-graded sand", "Strong foundation, excellent drainage."),
    "SP": ("Poorly graded sand", "Uniform sand, check for liquefaction risk."),
    "SM": ("Silty sand", "Erosion sensitive, fair stability."),
    "SC": ("Clayey sand", "Low permeability, stable when compacted."),
    "ML": ("Silt (Low Plasticity)", "Poor drainage, high frost susceptibility."),
    "MI": ("Silt (Intermediate Plasticity)", "Moderate compressibility, stable if dry."),
    "MH": ("Silt (High Plasticity)", "Highly elastic, poor for foundations."),
    "CL": ("Clay (Low Plasticity)", "Medium toughness, predictable settlement."),
    "CI": ("Clay (Intermediate Plasticity)", "Medium compressibility, good for embankments."),
    "CH": ("Clay (High Plasticity)", "High swelling potential (Black Cotton Soil type)."),
    "CL-ML": ("Silty Clay (Transition)", "Dual behavior, common in low plasticity zones."),
    "GW-GC": ("Well-graded gravel with clay", "Very high stability, low drainage."),
    "GP-GC": ("Poorly graded gravel with clay", "Stable base, check grading."),
    "GW-GM": ("Well-graded gravel with silt", "Good stability, check frost."),
    "GP-GM": ("Poorly graded gravel with silt", "Fair stability, uniform grading."),
    "SW-SC": ("Well-graded sand with clay", "Good for pavement subgrade."),
    "SP-SC": ("Poorly graded sand with clay", "Stable, check permeability."),
    "SW-SM": ("Well-graded sand with silt", "Good drainage, erosion prone."),
    "SP-SM": ("Poorly graded sand with silt", "Uniform sand, fair drainage.")
}

# 2. Enhanced PDF Class
class DigiSoilPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'MITS-DU Gwalior - Department of Civil Engineering', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 5, 'DigiSoil Automation System 2026', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by DigiSoil', 0, 0, 'C')

def create_pdf(data_dict, symbol, desc, rec):
    pdf = DigiSoilPDF()
    pdf.add_page()
    
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="Soil Classification Report (IS 1498)", ln=True, align='C')
    pdf.ln(5)

    # Info Header
    pdf.set_font("Arial", '', 10)
    pdf.cell(100, 6, txt=f"Developer: Diya Sharma (BTCE24O1027)", ln=True)
    pdf.cell(100, 6, txt=f"Date: {datetime.now().strftime('%d-%m-%Y %H:%M')}", ln=True)
    pdf.ln(5)

    # Parameters Table
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(110, 8, "Engineering Parameter", 1, 0, 'L', True)
    pdf.cell(80, 8, "Value", 1, 1, 'C', True)
    
    pdf.set_font("Arial", '', 10)
    for k, v in data_dict.items():
        pdf.cell(110, 7, txt=str(k), border=1)
        pdf.cell(80, 7, txt=str(v), border=1, ln=True, align='C')

    # Final Result Box
    pdf.ln(10)
    pdf.set_fill_color(255, 245, 245)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(190, 12, txt=f"CLASSIFICATION SYMBOL: {symbol}", border=1, ln=True, align='C', fill=True)
    
    pdf.set_font("Arial", 'I', 11)
    pdf.multi_cell(190, 8, txt=f"Description: {desc}", border='LR')
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(190, 8, txt="Recommendation:", border='LR', ln=True)
    pdf.set_font("Arial", '', 10)
    pdf.multi_cell(190, 7, txt=rec, border='LRB')

    return pdf.output(dest='S').encode('latin-1')

def run():
    st.header("📑 IS 1498 Final Classification")
    st.info("DigiSoil '26 | MITS-DU Gwalior")

    # --- 1. DATA RETRIEVAL ---
    gsd = st.session_state.get("gsd_final", {})
    ll = st.session_state.get("liquid_limit_val")
    pl = st.session_state.get("plastic_limit_val")
    
    # Check if a new GSD was performed but LL/PL are missing (Reset Check)
    if not gsd or ll is None or pl is None:
        if "res_symbol" in st.session_state:
            del st.session_state.res_symbol
        if "classified" in st.session_state:
            del st.session_state.classified

        st.warning("⚠️ **Insufficient Data:** Soil classification requires complete Sieve Analysis and Atterberg Limit tests.")
        
        c1, c2, c3 = st.columns(3)
        c1.write(f"GSD: {'✅' if gsd else '❌'}")
        c2.write(f"Liquid Limit: {'✅' if ll is not None else '❌'}")
        c3.write(f"Plastic Limit: {'✅' if pl is not None else '❌'}")
        
        st.info("Please finish all tests before generating the final symbol to ensure engineering accuracy.")
        return 

    # --- 2. CALCULATION & DASHBOARD ---
    # Now we are safe to calculate PI
    pi = ll - pl
    fines = gsd.get("fines", 0.0)
    gravel = gsd.get("gravel", 0.0)
    sand = gsd.get("sand", 0.0)
    cu = gsd.get("cu", 0.0)
    cc = gsd.get("cc", 0.0)
    
    # DASHBOARD DISPLAY
    st.subheader("📊 Collected Test Results")
    col1, col2, col3 = st.columns(3)
    col1.metric("Gravel / Sand / Fines", f"{gravel:.1f}/{sand:.1f}/{fines:.1f}")
    col2.metric("Liquid Limit (LL)", f"{ll:.1f}%")
    col3.metric("Plasticity Index (PI)", f"{pi:.1f}%")

    # --- 3. CLASSIFICATION LOGIC ---
    if st.button("🚀 Generate IS Classification", use_container_width=True):
        symbol = "Unknown"
        a_line = 0.73 * (ll - 20)
        
        # COARSE GRAINED SOIL
        if fines < 50:
            prefix = "G" if gravel > sand else "S"
            if prefix == "G":
                is_well = (cu > 4 and 1 <= cc <= 3)
            else:
                is_well = (cu > 6 and 1 <= cc <= 3)
            
            grad = "W" if is_well else "P"
            
            if fines < 5:
                symbol = f"{prefix}{grad}"
            elif fines > 12:
                suffix = "C" if (pi > 7 and pi > a_line) else "M"
                symbol = f"{prefix}{suffix}"
            else: # Dual Symbols (5-12% fines)
                suffix = "C" if (pi > 7 and pi > a_line) else "M"
                symbol = f"{prefix}{grad}-{prefix}{suffix}"
        
        # FINE GRAINED SOIL
        else:
            compressibility = "L" if ll < 35 else "I" if ll <= 50 else "H"
            if 4 <= pi <= 7 and (ll < 35) and (pi >= a_line):
                symbol = "CL-ML"
            else:
                kind = "C" if pi > a_line else "M"
                symbol = f"{kind}{compressibility}"

        st.session_state.res_symbol = symbol
        st.session_state.classified = True
        st.balloons()

    # --- 4. REPORT GENERATION ---
    if st.session_state.get("classified"):
        symbol = st.session_state.res_symbol
        desc, rec = IS_DATA.get(symbol, ("Soil Identified", "Refer to IS 1498 Manual."))
        
        st.success(f"### Resulting IS Symbol: **{symbol}**")
        st.markdown(f"**Description:** {desc}")
        
        report_data = {
            "Gravel Content (%)": f"{gravel:.2f}",
            "Sand Content (%)": f"{sand:.2f}",
            "Fines Content (%)": f"{fines:.2f}",
            "Liquid Limit (%)": f"{ll:.2f}",
            "Plastic Limit (%)": f"{pl:.2f}",
            "Plasticity Index (%)": f"{pi:.2f}",
            "Uniformity Coeff (Cu)": f"{cu:.2f}" if cu else "N/A",
            "Curvature Coeff (Cc)": f"{cc:.2f}" if cc else "N/A"
        }

        pdf_bytes = create_pdf(report_data, symbol, desc, rec)
        st.download_button(
            label="📥 Download Detailed PDF Report",
            data=pdf_bytes,
            file_name=f"DigiSoil_Report_{symbol}.pdf",
            mime="application/pdf",
            use_container_width=True
        )

    st.divider()
    if st.button("🏠 Back to Home", use_container_width=True):
        st.session_state.nav_choice = "Home"
        st.rerun()
